<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ik53A3EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ik53A3E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ik53A3E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'utils' => ['privates', 'App\\Utils\\Utils', 'getUtilsService', true],
        ], [
            'utils' => 'App\\Utils\\Utils',
        ]);
    }
}
