<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Lqzh0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._.lqzh0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._.lqzh0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator._.lqzh0.App\\Entity\\Circuit', NULL, 'Cannot autowire service ".service_locator._.lqzh0": it references class "App\\Entity\\Circuit" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Circuit',
            'repo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
