<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZpV5aXYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZpV5aXY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZpV5aXY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\CircuitRepository',
        ]);
    }
}
