<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P5rdrQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P5rdrQL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P5rdrQL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'utils' => ['privates', 'App\\Utils\\Utils', 'getUtilsService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\CircuitRepository',
            'utils' => 'App\\Utils\\Utils',
        ]);
    }
}
