<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SW5dS_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sW5dS.C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sW5dS.C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'repoC' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
            'repoI' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
            'repoU' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'mailer' => '?',
            'repoC' => 'App\\Repository\\CircuitRepository',
            'repoI' => 'App\\Repository\\InscriptionRepository',
            'repoU' => 'App\\Repository\\UserRepository',
        ]);
    }
}
