<?php

namespace ContainerKiNqU4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HbCQ95KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HbCQ95K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HbCQ95K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.HbCQ95K.App\\Entity\\Circuit', NULL, 'Cannot autowire service ".service_locator.HbCQ95K": it references class "App\\Entity\\Circuit" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Circuit',
            'em' => '?',
            'mailer' => '?',
            'repo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
