<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKiNqU4v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKiNqU4v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKiNqU4v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKiNqU4v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKiNqU4v\App_KernelDevDebugContainer([
    'container.build_hash' => 'KiNqU4v',
    'container.build_id' => 'b6d1ea1f',
    'container.build_time' => 1623855390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKiNqU4v');
